<a href="https://colab.research.google.com/github/jonahyuan/AI-learning/blob/main/01_RNN_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [7]:
# Sample(batch) size: 1
# Sequence Length: 5
# feature dimension: 8

inputs = tf.random.normal([1, 5, 8])
inputs.shape

TensorShape([1, 5, 8])

# tf.keras.layers.LSTM

In [8]:
output = layers.LSTM(units=3)(inputs)
output2 = layers.LSTM(units=3, return_sequences=True)(inputs)
print(output.shape) # (batch size, feature dim)
print(output2.shape) # (batch size, seq length, feature dim)

(1, 3)
(1, 5, 3)


In [9]:
whole_seq_output, final_hiden_state, final_cell_state = layers.LSTM(units=3, 
                                    return_sequences=True, 
                                    return_state=True)(inputs)

print('whole_seq_output: ', whole_seq_output.shape, whole_seq_output)
print('final_hiden_state (h): ', final_hiden_state.shape, final_hiden_state)
print('final_cell_state (c): ', final_cell_state.shape, final_cell_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[ 0.31856534  0.16057138 -0.05621225]
  [ 0.10652287  0.17176747  0.11731825]
  [ 0.11528575  0.3920101  -0.00341319]
  [ 0.12605466  0.17167641 -0.11784741]
  [ 0.17258821  0.1490932  -0.07279466]]], shape=(1, 5, 3), dtype=float32)
final_hiden_state (h):  (1, 3) tf.Tensor([[ 0.17258821  0.1490932  -0.07279466]], shape=(1, 3), dtype=float32)
final_cell_state (c):  (1, 3) tf.Tensor([[ 0.31824067  0.66747427 -0.23019215]], shape=(1, 3), dtype=float32)


# tf.keras.layers.GRU

In [10]:
output = layers.GRU(units=3)(inputs)
print(output.shape)

(1, 3)


In [11]:
whole_sequence_output, final_state = layers.GRU(3, 
                                                return_sequences=True, 
                                                return_state=True)(inputs)

print('whole_seq_output: ', whole_sequence_output.shape, whole_sequence_output)
print('final_state (h): ', final_state.shape, final_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[-0.27897793  0.2748221  -0.0780917 ]
  [-0.3488952   0.38123488 -0.13137235]
  [-0.27987546  0.10400359 -0.17405552]
  [-0.2157981   0.10614604 -0.64313424]
  [-0.02492946  0.43839735 -0.42062473]]], shape=(1, 5, 3), dtype=float32)
final_state (h):  (1, 3) tf.Tensor([[-0.02492946  0.43839735 -0.42062473]], shape=(1, 3), dtype=float32)


# tf.keras.layers.Bidirectional

In [12]:
output = layers.Bidirectional(layers.LSTM(3))(inputs)
print(output.shape)

(1, 6)


In [14]:
# merge_mode: 'sum' or 'concat'
output = layers.Bidirectional(layers.LSTM(3), 
                merge_mode='sum')(inputs)
print(output.shape)

(1, 3)


In [15]:
# return_sequences: True
output = layers.Bidirectional(layers.LSTM(3, return_sequences=True))(inputs)
print(output.shape)

(1, 5, 6)


In [16]:
# return_sequences: True, 
output, forward_h, forward_c, backward_h, backward_c = layers.Bidirectional(layers.LSTM(3, 
                                        return_sequences=True, 
                                        return_state=True))(inputs)
print('output : ', output.shape, output)
print('forward_h : ', forward_h.shape, forward_h)
print('forward_c : ', forward_c.shape, forward_c)
print('backward_h : ', backward_h.shape, backward_h)
print('backward_c : ', backward_c.shape, backward_c)


output :  (1, 5, 6) tf.Tensor(
[[[-0.00176525  0.0965874   0.11226808  0.19828662 -0.06742185
    0.21241425]
  [-0.47356242  0.17757232  0.13894878  0.02178642 -0.12409721
    0.22645907]
  [-0.28605255  0.3405394   0.08328305  0.57680625  0.06336416
    0.01047394]
  [-0.08044696  0.1830515   0.18109919  0.32229722  0.1637661
   -0.02895554]
  [-0.02617154  0.02284603  0.0656488   0.03101021 -0.00366895
    0.14665459]]], shape=(1, 5, 6), dtype=float32)
forward_h :  (1, 3) tf.Tensor([[-0.02617154  0.02284603  0.0656488 ]], shape=(1, 3), dtype=float32)
forward_c :  (1, 3) tf.Tensor([[-0.10588103  0.0461117   0.09769522]], shape=(1, 3), dtype=float32)
backward_h :  (1, 3) tf.Tensor([[ 0.19828662 -0.06742185  0.21241425]], shape=(1, 3), dtype=float32)
backward_c :  (1, 3) tf.Tensor([[ 0.26249495 -0.12688397  0.39798   ]], shape=(1, 3), dtype=float32)


## Many-to-one

In [25]:
input = layers.Input(shape=(5, 8)) # (seq len, feature dim)
x = layers.LSTM(3)(input)
ouput = layers.Dense(10, activation='softmax')(x)
model = models.Model(input, ouput)
model.summary()

Model: "model_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_9 (InputLayer)        [(None, 5, 8)]            0         
                                                                 
 lstm_25 (LSTM)              (None, 3)                 144       
                                                                 
 dense_8 (Dense)             (None, 10)                40        
                                                                 
Total params: 184
Trainable params: 184
Non-trainable params: 0
_________________________________________________________________


In [19]:
# multi-layer
input = layers.Input(shape=(5, 8))
x1 = layers.LSTM(128, return_sequences=True)(input)
x2 = layers.LSTM(256, return_sequences=True)(x1)
x3 = layers.LSTM(512)(x2)
ouput = layers.Dense(10, activation='softmax')(x3)
model = models.Model(input, ouput)
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 5, 8)]            0         
                                                                 
 lstm_17 (LSTM)              (None, 5, 128)            70144     
                                                                 
 lstm_18 (LSTM)              (None, 5, 256)            394240    
                                                                 
 lstm_19 (LSTM)              (None, 512)               1574912   
                                                                 
 dense_2 (Dense)             (None, 10)                5130      
                                                                 
Total params: 2,044,426
Trainable params: 2,044,426
Non-trainable params: 0
_________________________________________________________________


# Many-to-many (same length)

In [21]:
input = layers.Input(shape=(500, 8))
x = layers.LSTM(10, 
          return_sequences=True)(input)
          
output = layers.Dense(20, activation='softmax')(x)
model = models.Model(input, output)
model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 500, 8)]          0         
                                                                 
 lstm_21 (LSTM)              (None, 500, 10)           760       
                                                                 
 dense_4 (Dense)             (None, 500, 20)           220       
                                                                 
Total params: 980
Trainable params: 980
Non-trainable params: 0
_________________________________________________________________


## Many-to-many (different length) : Seq2seq

In [ ]:
# Video RNN
# 10sec, 30fps, (200,200,3)
# (1, 300, 200, 200, 3): Video
# (1, 300, 1024) : video frame feature




In [ ]:
token

The song was featured in the musical Can-Can when it was introduced by the French actress Lilo.

token

The song was featured in the musical Can-Can.

Tokenize (word, character)

In [ ]:
sentence = "The song was featured in the musical Can-Can ."
sentence.split(' ')

['The', 'song', 'was', 'featured', 'in', 'the', 'musical', 'Can-Can', '.']

In [ ]:
"粉絲數超過0的網紅"
中文：詞, 字

斷詞: jieba
"粉絲, 數, 超過, 0, 的, 網紅" (6, )
"粉絲數, 超過, 0, 的, 網紅" (5, )

斷字
"粉, 絲, 數, 超, 過, 0 , 的, 網 , 紅"

[120, 130, 200, 400, 222, 40]

(1, 6)


Embedding: convert token to vector
128,

(1, 6, 128)